### PR TITLE
Support more type coercion

### PR DESCRIPTION
**Pull request by schmichael**
There are some paths in binary expression handling in the VM where we don't cover all possible type conversions.

### CODE REVIEW

**Comment by araddon** [comment]
would we be able to test this?  
https://github.com/schmichael/qlbridge/blob/f991350d2bcda5b5ac464f873f7c6e165a12efe1/vm/filterqlvm_test.go#L100

**Comment by kyledj** [comment]
:baseball::baseball::baseball:
:baseball::frog::baseball:
:baseball::baseball::baseball:

**Comment by schmichael** [comment]
@araddon good call! Added.

**Comment by araddon** [comment]
:+1:

**Pull request merged**
